### ISSUE TITLE
Missions Button is detached from minimap every time

### ISSUE THREAD

**Issue by Gal10** [Ravendwyr/Chinchilla#59] opened 2020-10-28 12:44 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**WoW version**
Are you running this addon on Retail or Classic servers?

**Additional context**

**Comment by stoglim** [comment] 2020-10-28 13:33
duplicate of https://github.com/Ravendwyr/Chinchilla/issues/53

**Closed** 2020-10-28 18:03 UTC
Labels: duplicate
