### ISSUE TITLE
Tracking dots not working.

### ISSUE THREAD

**Issue by griddark** [Ravendwyr/Chinchilla#71] opened 2020-12-17 06:49 UTC
**Describe the bug**
Tracking dots not working properly.

**To Reproduce**
Select different tracking dots.

**Expected behavior**
Tracking dots change to expected appearence.

**Screenshots**
https://puu.sh/GRSax/ee9f2a8620.jpg

**WoW version**
Retail

**Additional context**
Just adding bug, headlinerko posted in comments, I also experienced it.

**Comment by Ravendwyr** [comment] 2021-01-03 13:13
Duplicate of #48 and #63

**Closed by Ravendwyr** 2021-01-03 13:13 UTC
