### ISSUE TITLE
Vehicle Seat Indicator

### ISSUE THREAD

**Issue by Hmmharold** [Ravendwyr/Chinchilla#76] opened 2021-02-15 13:17 UTC
Can you please add a mover for the Vehicle Seat Indicator?

**Comment by Hmmharold** [comment] 2021-02-15 14:31
My apologies! I noticed this feature was already added to the LUA on GitHub but not uploaded to the Curseforge bundle

**Comment by Ravendwyr** [comment] 2021-02-16 00:57
I really should update the CurseForge package. :/
Closing this as a dupe of #44, #66, and #75 for now.

**Closed by Ravendwyr** 2021-02-16 00:57 UTC
Labels: enhancement
