### ISSUE TITLE
2 Lua errors

### ISSUE THREAD

**Issue by zalidthebur** [Ravendwyr/Chinchilla#58] opened 2020-10-19 20:36 UTC
I had hoped the update from 2 days ago would solve these, but sadly they are still present. I have uninstalled and installed v2.10.2

Error 1:
12x Chinchilla\Modules\Location.lua:43: attempt to call method 'SetBackdrop' (a nil value)
[string "@Chinchilla\Modules\Location.lua"]:43: in function <Chinchilla\Modules\Location.lua:33>
[string "=[C]"]: ?
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:540: in function `EnableAddon'
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:615>

Error 2:
12x Chinchilla\Modules\Ping.lua:49: attempt to call method 'SetBackdrop' (a nil value)
[string "@Chinchilla\Modules\Ping.lua"]:49: in function <Chinchilla\Modules\Ping.lua:37>
[string "=[C]"]: ?
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:540: in function `EnableAddon'
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:615>

**Comment by Ravendwyr** [comment] 2020-10-19 21:26
Duplicate of #48

**Closed by Ravendwyr** 2020-10-19 21:26 UTC
